### ISSUE TITLE
Provide cross-platform support

### ISSUE THREAD

**Issue by ed-george** [ed-george/adbp#1]
At present, adbp has only been tested on macOS and requires testing/modification on other platforms. There are likely some changes that need to be made to work as expected on Windows machines.

The aim is to provide consistent functionality across all platforms.

**Comment by svenkat19** [comment]
Would be glad to help you for Windows machines.

**Comment by ed-george** [comment]
@svenkat19 please feel free!

The main aspects that will not work on Windows are:

- Running adb (?)
- Finding the default ip address
- Getting the list of ADB devices and splitting them into a list of their serial numbers

I am sure for each of these there is a better solution that is platform agnostic and utilises a standard python approach, but sadly I am no python dev, so I have yet to look into it.

Please let me know if this makes sense!
